# import required libraries

In [1]:
import pandas as pd
import numpy as np

# Question 1 :

In [2]:
pd.__version__

'2.1.0'

In [10]:
df = pd.read_csv("../data/w1.csv")

# Question 2 :

In [11]:
columns_length = len(df.columns)
print(f"Total number of columns : {columns_length}")

Total number of columns : 10


# Question 3 :

In [12]:
df.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

# Question 4 :

In [13]:
# len(df['ocean_proximity'].unique())
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

# Question 5 :

In [14]:
# df[df['ocean_proximity'] == 'NEAR BAY']
df["median_house_value"][df['ocean_proximity'] == 'NEAR BAY'].mean()


259212.31179039303

# Question 6 :

In [15]:
df["total_bedrooms"].mean()

537.8705525375618

In [16]:
df['total_bedrooms'] =  df['total_bedrooms'].fillna(df["total_bedrooms"].mean())

In [17]:
df["total_bedrooms"].mean()

537.8705525375617

# Question 7 :

In [18]:
df[df['ocean_proximity'] == 'ISLAND']

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [28]:
sel_col = ["housing_median_age", "total_rooms", "total_bedrooms"]
X = np.array(df[sel_col][df['ocean_proximity'] == 'ISLAND'])
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [29]:
XTX = np.matmul(X.T, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [30]:
X.dot(X.T)


array([[3077795., 4260640., 3830881., 1807248., 1311577.],
       [4260640., 5916866., 5322889., 2508292., 1817026.],
       [3830881., 5322889., 4788977., 2256364., 1634008.],
       [1807248., 2508292., 2256364., 1064416.,  771140.],
       [1311577., 1817026., 1634008.,  771140.,  559293.]])

In [31]:
## inverse of the XTX
i_XTX = np.linalg.inv(XTX)
i_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [32]:
y = np.array([950, 1300, 800, 1000, 1300])

In [34]:
w = (i_XTX.dot(X.T)).dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])